/**
 * Dublin Bus & Bus Éireann Realtime MCP — Cloudflare Worker
 * Implements MCP Streamable HTTP (JSON-RPC over POST)
 * Data source: NTA GTFS-R v2 API (National Transport Authority)
 *
 * Requires secret: NTA_API_KEY
 *   wrangler secret put NTA_API_KEY
 */

import routesData from "./routes.generated.json";

const NTA_BASE = "https://api.nationaltransport.ie/gtfsr/v2";

interface RouteInfo {
  short_name: string;
  agency_id: string;
  agency_name: string;
}

const ROUTES: Record<string, RouteInfo> = (routesData as { routes: Record<string, RouteInfo> }).routes;

// Maps logical operator → predicate on agency_name from static GTFS.
// The realtime feed exposes only route_id, so we resolve route_id → agency
// via the static feed (regenerated by `npm run update-routes`).
function operatorMatches(agencyName: string, operator: string | null): boolean {
  if (!operator) return true;
  const a = agencyName.toLowerCase();
  switch (operator) {
    case "dublin_bus": return a.includes("dublin bus") || a.includes("bus átha cliath");
    case "bus_eireann": return a.includes("bus éireann") || a.includes("bus eireann");
    case "go_ahead": return a.includes("go-ahead");
    default: return true;
  }
}

export interface Env {
  NTA_API_KEY: string;
}

// ─── Types ────────────────────────────────────────────────────────────────────

interface GtfsTrip {
  trip_id?: string;
  route_id?: string;
  direction_id?: number;
  schedule_relationship?: string;
}

interface GtfsVehicleDescriptor {
  id?: string;
  label?: string;
}

interface GtfsPosition {
  latitude?: number;
  longitude?: number;
  bearing?: number;
  speed?: number;
}

interface GtfsVehiclePosition {
  trip?: GtfsTrip;
  vehicle?: GtfsVehicleDescriptor;
  position?: GtfsPosition;
  current_stop_sequence?: number;
  current_status?: string;
  timestamp?: string | number;
}

interface GtfsStopTimeUpdate {
  stop_sequence?: number;
  stop_id?: string;
  arrival?: { delay?: number; time?: string | number };
  departure?: { delay?: number; time?: string | number };
  schedule_relationship?: string;
}

interface GtfsTripUpdate {
  trip?: GtfsTrip;
  vehicle?: GtfsVehicleDescriptor;
  stop_time_update?: GtfsStopTimeUpdate[];
}

interface GtfsTranslation {
  text?: string;
  language?: string;
}

interface GtfsInformedEntity {
  agency_id?: string;
  route_id?: string;
  route_type?: number;
  trip?: GtfsTrip;
  stop_id?: string;
}

interface GtfsAlert {
  active_period?: Array<{ start?: number; end?: number }>;
  informed_entity?: GtfsInformedEntity[];
  cause?: string;
  effect?: string;
  url?: { translation?: GtfsTranslation[] };
  header_text?: { translation?: GtfsTranslation[] };
  description_text?: { translation?: GtfsTranslation[] };
}

interface GtfsEntity {
  id: string;
  vehicle?: GtfsVehiclePosition;
  trip_update?: GtfsTripUpdate;
  alert?: GtfsAlert;
}

interface GtfsFeed {
  header?: { gtfs_realtime_version?: string; timestamp?: string | number };
  entity?: GtfsEntity[];
}

// ─── NTA API ──────────────────────────────────────────────────────────────────

async function ntaFetch(endpoint: string, apiKey: string): Promise<GtfsFeed> {
  const url = `${NTA_BASE}/${endpoint}?format=json`;
  const res = await fetch(url, {
    headers: {
      "x-api-key": apiKey,
      "User-Agent": "IrishMCP/1.0 (+https://irishmcp.ie)",
      "Cache-Control": "no-cache",
    },
  });
  if (!res.ok) throw new Error(`NTA API error ${res.status}: ${await res.text()}`);
  return res.json() as Promise<GtfsFeed>;
}

// ─── Filtering helpers ────────────────────────────────────────────────────────

function routeIdMatchesOperator(routeId: string, operator: string | null): boolean {
  if (!operator) return true;
  const info = ROUTES[routeId];
  if (!info) return false;
  return operatorMatches(info.agency_name, operator);
}

function routeIdMatchesRoute(routeId: string, routeNumber: string | null): boolean {
  if (!routeNumber) return true;
  const info = ROUTES[routeId];
  if (!info) return false;
  return info.short_name.toLowerCase() === routeNumber.toLowerCase();
}

function extractRouteNumber(routeId: string): string {
  return ROUTES[routeId]?.short_name ?? routeId;
}

function getTranslation(t: { translation?: GtfsTranslation[] } | undefined): string {
  if (!t?.translation?.length) return "";
  const en = t.translation.find(x => x.language === "en" || !x.language);
  return (en ?? t.translation[0])?.text ?? "";
}

function formatStatus(s: string | undefined): string {
  const map: Record<string, string> = {
    INCOMING_AT: "Approaching",
    STOPPED_AT: "Stopped",
    IN_TRANSIT_TO: "In transit",
  };
  return s ? (map[s] ?? s) : "Unknown";
}

function formatDelaySecs(secs: number): string {
  if (secs === 0) return "On time";
  const abs = Math.abs(secs);
  const mins = Math.round(abs / 60);
  return secs > 0 ? `${mins} min late` : `${mins} min early`;
}

// ─── Tool Implementations ─────────────────────────────────────────────────────

async function getVehiclePositions(
  apiKey: string,
  routeNumber: string | null,
  operator: string | null,
  limit = 30,
): Promise<string> {
  const feed = await ntaFetch("Vehicles", apiKey);
  const entities = feed.entity ?? [];

  const matches = entities
    .filter(e => {
      const rid = e.vehicle?.trip?.route_id ?? "";
      return routeIdMatchesOperator(rid, operator) && routeIdMatchesRoute(rid, routeNumber);
    })
    .slice(0, limit);

  if (!matches.length) {
    const who = routeNumber ? `route ${routeNumber}` : (operator ?? "all operators");
    return `No vehicles currently tracked for ${who}. The service may not be running right now.`;
  }

  const ts = feed.header?.timestamp
    ? new Date(Number(feed.header.timestamp) * 1000).toISOString()
    : "unknown";

  const lines: string[] = [
    `${matches.length} bus(es) tracked (feed updated ${ts}):`,
    "",
  ];

  for (const e of matches) {
    const v = e.vehicle!;
    const rid = v.trip?.route_id ?? "";
    const route = extractRouteNumber(rid);
    const dir = v.trip?.direction_id === 0 ? "Outbound" : "Inbound";
    const status = formatStatus(v.current_status);
    const lat = v.position?.latitude?.toFixed(5) ?? "?";
    const lng = v.position?.longitude?.toFixed(5) ?? "?";
    const label = v.vehicle?.label ?? v.vehicle?.id ?? "?";
    const speed = v.position?.speed != null
      ? ` | ${(v.position.speed * 3.6).toFixed(0)} km/h`
      : "";

    lines.push(`  Route ${route} [${dir}] — Bus ${label}`);
    lines.push(`    Status: ${status} | GPS: ${lat}, ${lng}${speed}`);
    lines.push("");
  }

  if (entities.length > limit) {
    lines.push(`  (showing ${limit} of ${entities.length} total vehicles)`);
  }

  return lines.join("\n");
}

async function getTripUpdates(
  apiKey: string,
  routeNumber: string | null,
  operator: string | null,
  limit = 30,
): Promise<string> {
  const feed = await ntaFetch("TripUpdates", apiKey);
  const entities = feed.entity ?? [];

  const matches = entities
    .filter(e => {
      const rid = e.trip_update?.trip?.route_id ?? "";
      return routeIdMatchesOperator(rid, operator) && routeIdMatchesRoute(rid, routeNumber);
    })
    .slice(0, limit);

  if (!matches.length) {
    const who = routeNumber ? `route ${routeNumber}` : (operator ?? "all operators");
    return `No trip updates found for ${who}.`;
  }

  const ts = feed.header?.timestamp
    ? new Date(Number(feed.header.timestamp) * 1000).toISOString()
    : "unknown";

  const lines: string[] = [
    `${matches.length} trip update(s) (feed ${ts}):`,
    "",
  ];

  for (const e of matches) {
    const tu = e.trip_update!;
    const rid = tu.trip?.route_id ?? "";
    const route = extractRouteNumber(rid);
    const dir = tu.trip?.direction_id === 0 ? "Outbound" : "Inbound";
    const vehicle = tu.vehicle?.label ?? tu.vehicle?.id ?? "?";

    lines.push(`  Route ${route} [${dir}] — Vehicle ${vehicle}`);

    const updates = tu.stop_time_update ?? [];
    // Show worst delay across stops
    let maxDelay = 0;
    for (const stu of updates) {
      const d = stu.arrival?.delay ?? stu.departure?.delay ?? 0;
      if (Math.abs(d) > Math.abs(maxDelay)) maxDelay = d;
    }
    if (maxDelay !== 0) {
      lines.push(`    Delay: ${formatDelaySecs(maxDelay)}`);
    } else {
      lines.push(`    On time`);
    }

    // Next stop
    const next = updates[0];
    if (next?.stop_id) {
      const depDelay = next.departure?.delay ?? 0;
      lines.push(`    Next stop: ${next.stop_id} (${formatDelaySecs(depDelay)})`);
    }

    lines.push("");
  }

  return lines.join("\n");
}

async function getAlerts(
  apiKey: string,
  routeNumber: string | null,
  operator: string | null,
): Promise<string> {
  const feed = await ntaFetch("Alerts", apiKey);
  const entities = feed.entity ?? [];

  const now = Math.floor(Date.now() / 1000);

  const matches = entities.filter(e => {
    const a = e.alert;
    if (!a) return false;

    // Active period check
    if (a.active_period?.length) {
      const active = a.active_period.some(p => {
        const start = p.start ?? 0;
        const end = p.end ?? Infinity;
        return now >= start && now <= end;
      });
      if (!active) return false;
    }

    // Route/operator filter
    if (routeNumber || operator) {
      return (a.informed_entity ?? []).some(ie => {
        const rid = ie.route_id ?? "";
        return routeIdMatchesOperator(rid, operator) && routeIdMatchesRoute(rid, routeNumber);
      });
    }

    return true;
  });

  if (!matches.length) {
    const who = routeNumber
      ? `route ${routeNumber}`
      : operator
        ? operator.replace("_", " ")
        : "all operators";
    return `No active service alerts for ${who}.`;
  }

  const lines: string[] = [`${matches.length} active alert(s):`, ""];

  for (const e of matches) {
    const a = e.alert!;
    const header = getTranslation(a.header_text);
    const desc = getTranslation(a.description_text);
    const effect = a.effect ?? "UNKNOWN_EFFECT";
    const cause = a.cause ?? "UNKNOWN_CAUSE";

    const affectedRoutes = (a.informed_entity ?? [])
      .filter(ie => ie.route_id)
      .map(ie => extractRouteNumber(ie.route_id!))
      .filter((r, i, arr) => arr.indexOf(r) === i)
      .slice(0, 10);

    lines.push(`  [${effect}] ${header || "(no title)"}`);
    if (affectedRoutes.length) lines.push(`    Routes: ${affectedRoutes.join(", ")}`);
    if (cause !== "UNKNOWN_CAUSE") lines.push(`    Cause: ${cause}`);
    if (desc) lines.push(`    ${desc.slice(0, 300)}${desc.length > 300 ? "…" : ""}`);
    lines.push("");
  }

  return lines.join("\n");
}

// ─── Natural Language Query ───────────────────────────────────────────────────

async function naturalLanguageQuery(query: string, apiKey: string): Promise<string> {
  const q = query.toLowerCase();

  // Detect operator
  let operator: string | null = null;
  if (q.includes("dublin bus") || q.includes("dublinbus")) operator = "dublin_bus";
  else if (q.includes("bus éireann") || q.includes("bus eireann") || q.includes("buseireann")) operator = "bus_eireann";
  else if (q.includes("go-ahead") || q.includes("go ahead") || q.includes("goahead")) operator = "go_ahead";

  // Detect route number (e.g. 46A, 16, 101, X1, XE)
  const routeMatch = query.match(/\b(\d{1,3}[A-Za-z]?|X[A-Za-z0-9]+)\b/);
  const routeNumber = routeMatch ? routeMatch[1].toUpperCase() : null;

  // Detect intent
  if (q.includes("alert") || q.includes("disruption") || q.includes("cancel")) {
    return getAlerts(apiKey, routeNumber, operator);
  }

  if (q.includes("delay") || q.includes("late") || q.includes("on time") || q.includes("update")) {
    return getTripUpdates(apiKey, routeNumber, operator, 30);
  }

  if (q.includes("where") || q.includes("position") || q.includes("location") || q.includes("gps") || q.includes("track")) {
    return getVehiclePositions(apiKey, routeNumber, operator, 30);
  }

  // Route-specific query → vehicle positions first
  if (routeNumber) {
    return getVehiclePositions(apiKey, routeNumber, operator, 20);
  }

  // Operator-only query → trip updates
  if (operator) {
    return getTripUpdates(apiKey, null, operator, 20);
  }

  // Default: show alerts then prompt
  const alerts = await getAlerts(apiKey, null, null);
  return alerts + "\nTip: Ask for a specific route (e.g. \"46A positions\"), delays, or alerts.";
}

// ─── MCP Tool Definitions ─────────────────────────────────────────────────────

const TOOLS = [
  {
    name: "query",
    description:
      "Natural language query for Dublin Bus & Bus Éireann realtime data. Ask about a route's position, delays, or service alerts.",
    inputSchema: {
      type: "object",
      properties: {
        query: {
          type: "string",
          description:
            'e.g. "where is the 46A?", "Dublin Bus 16 delays", "Bus Éireann X1 alerts", "route 101 position"',
        },
      },
      required: ["query"],
    },
  },
  {
    name: "get_vehicle_positions",
    description:
      "Get real-time GPS positions and status of buses currently on the road. Optionally filter by route number and/or operator.",
    inputSchema: {
      type: "object",
      properties: {
        route_number: {
          type: "string",
          description: "Route number e.g. 46A, 16, 101, X1, X2 (optional)",
        },
        operator: {
          type: "string",
          enum: ["dublin_bus", "bus_eireann", "go_ahead", "all"],
          description: "Operator filter (default: all)",
        },
        limit: {
          type: "number",
          description: "Max results to return (default 30, max 100)",
        },
      },
      required: [],
    },
  },
  {
    name: "get_trip_updates",
    description:
      "Get real-time trip updates including delays and cancellations. Optionally filter by route and operator.",
    inputSchema: {
      type: "object",
      properties: {
        route_number: {
          type: "string",
          description: "Route number e.g. 46A, 16, 101 (optional)",
        },
        operator: {
          type: "string",
          enum: ["dublin_bus", "bus_eireann", "go_ahead", "all"],
          description: "Operator filter (default: all)",
        },
        limit: {
          type: "number",
          description: "Max results to return (default 30)",
        },
      },
      required: [],
    },
  },
  {
    name: "get_alerts",
    description:
      "Get active service alerts and disruptions for Dublin Bus and Bus Éireann routes.",
    inputSchema: {
      type: "object",
      properties: {
        route_number: {
          type: "string",
          description: "Filter by route number e.g. 46A, 16 (optional)",
        },
        operator: {
          type: "string",
          enum: ["dublin_bus", "bus_eireann", "go_ahead", "all"],
          description: "Filter by operator (default: all)",
        },
      },
      required: [],
    },
  },
];

// ─── Tool Dispatch ────────────────────────────────────────────────────────────

async function callTool(
  name: string,
  args: Record<string, unknown>,
  env: Env,
): Promise<string> {
  const route = args.route_number ? String(args.route_number) : null;
  const op = args.operator && args.operator !== "all" ? String(args.operator) : null;
  const limit = args.limit ? Math.min(Number(args.limit), 100) : 30;

  switch (name) {
    case "query":
      return naturalLanguageQuery(String(args.query ?? ""), env.NTA_API_KEY);
    case "get_vehicle_positions":
      return getVehiclePositions(env.NTA_API_KEY, route, op, limit);
    case "get_trip_updates":
      return getTripUpdates(env.NTA_API_KEY, route, op, limit);
    case "get_alerts":
      return getAlerts(env.NTA_API_KEY, route, op);
    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}

// ─── MCP JSON-RPC Handler ─────────────────────────────────────────────────────

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Accept",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS, "Content-Type": "application/json" },
  });
}

async function handleMCP(req: Request, env: Env): Promise<Response> {
  if (req.method === "OPTIONS") return new Response(null, { headers: CORS });

  if (req.method === "GET") {
    return json({
      name: "Dublin Bus & Bus Éireann Realtime MCP",
      version: "1.0.0",
      description: "Real-time Dublin Bus & Bus Éireann data via NTA GTFS-R",
      tools: TOOLS.map(t => t.name),
    });
  }

  if (req.method !== "POST")
    return new Response("Method Not Allowed", { status: 405, headers: CORS });

  let body: { jsonrpc?: string; method?: string; params?: unknown; id?: unknown };
  try {
    body = await req.json();
  } catch {
    return json(
      { jsonrpc: "2.0", error: { code: -32700, message: "Parse error" }, id: null },
      400,
    );
  }

  const id = body.id ?? null;
  const ok = (result: unknown) => json({ jsonrpc: "2.0", result, id });
  const err = (code: number, msg: string) =>
    json({ jsonrpc: "2.0", error: { code, message: msg }, id });

  switch (body.method) {
    case "initialize":
      return ok({
        protocolVersion: "2024-11-05",
        serverInfo: { name: "Dublin Bus & Bus Éireann Realtime MCP", version: "1.0.0" },
        capabilities: { tools: {} },
      });

    case "notifications/initialized":
      return new Response(null, { status: 204, headers: CORS });

    case "ping":
      return ok({});

    case "tools/list":
      return ok({ tools: TOOLS });

    case "tools/call": {
      const p = body.params as
        | { name?: string; arguments?: Record<string, unknown> }
        | undefined;
      if (!p?.name) return err(-32602, "Missing tool name");
      try {
        const text = await callTool(p.name, p.arguments ?? {}, env);
        return ok({ content: [{ type: "text", text }] });
      } catch (e) {
        return err(-32000, e instanceof Error ? e.message : "Tool failed");
      }
    }

    default:
      return err(-32601, `Method not found: ${body.method}`);
  }
}

// ─── Worker Entry Point ───────────────────────────────────────────────────────

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const { pathname } = new URL(request.url);

    if (pathname === "/mcp" || pathname === "/mcp/") return handleMCP(request, env);

    if (pathname === "/health") {
      return json({ status: "ok", service: "Dublin Bus & Bus Éireann Realtime MCP", version: "1.0.0" });
    }

    if (pathname === "/" || pathname === "") {
      return json({
        service: "Dublin Bus & Bus Éireann Realtime MCP",
        mcp_endpoint: "/mcp",
        tools: TOOLS.map(t => ({ name: t.name, description: t.description })),
      });
    }

    return new Response("Not Found", { status: 404, headers: CORS });
  },
};
